### ISSUE TITLE
Tag the 0.0.4 release here

### ISSUE THREAD

**Issue by pcowgill** [fvictorio/solhint-plugin-prettier#1]
On npm there is a `0.0.4` release now. Is this still the current repo? Thanks!

https://www.npmjs.com/package/solhint-plugin-prettier

**Comment by fvictorio** [comment]
Hey Paul, my user stopped watching this repo for some reason -_- Sorry for not answering before.

I'm not sure what you mean. Do you mean adding a git tag for that release?

(And yes, this is the current repo!)
