### ISSUE TITLE
Incompatible with Prettier 3

### ISSUE THREAD

**Issue by Yurii277** [fvictorio/solhint-plugin-prettier#14]
`prettier-plugin-solidity@1.1.3` conflicts with Prettier 3.0.3 during installation because of:
```
Could not resolve dependency:
npm WARN peer prettier@"^1.15.0 || ^2.0.0" from solhint-plugin-prettier@0.0.5
npm WARN node_modules/solhint-plugin-prettier
npm WARN   dev solhint-plugin-prettier@"^0.0.5" from the root project
```

Please, add compatibility for Prettier 3.

**Comment by PierrickGT** [comment]
There is an open PR here: https://github.com/fvictorio/solhint-plugin-prettier/pull/12
