### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by avatar-lavventura** [fvictorio/solhint-plugin-prettier#2]
contract/contracts/eBlocBroker.sol
[error] contract/contracts/eBlocBroker.sol: TypeError: Cannot read property 'filter' of undefined
[error]     at addBlockStatementFirstComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:186:26)
[error]     at handleIfStatementComments (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:265:5)
[error]     at handleEndOfLineComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/prettier-comments/language-js/comments.js:98:5)
[error]     at solidityHandleEndOfLineComment (/Users/alper/eBlocBroker/node_modules/prettier-plugin-solidity/src/comments/handler.js:55:5)
[error]     at /Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:12427:11
[error]     at Array.forEach (<anonymous>)
[error]     at Object.attach (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:12380:12)
[error]     at attachComments (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13241:14)
[error]     at coreFormat (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13270:21)
[error]     at format (/Users/alper/eBlocBroker/node_modules/prettier/bin-prettier.js:13516:73)

**Comment by fvictorio** [comment]
Hey @avatar-lavventura, my user stopped watching this repo for some reason. Sorry for not answering before!

Is this still happening to you? What version of each package are you using? And, if it's indeed happening, could you share the solidity code that triggers this issue?
