### ISSUE TITLE
Upgrade peer dependency on prettier to v2

### ISSUE THREAD

**Issue by PaulRBerg** [fvictorio/solhint-plugin-prettier#6]
I'm using prettier@2.0.5 and I'm getting this warning when running `yarn install` in a project that lists `solhint-plugin-prettier` as a dependency:

<img width="656" alt="Screenshot 2020-08-24 at 20 29 05" src="https://user-images.githubusercontent.com/8782666/91076750-9fb9a900-e648-11ea-86d6-4858ed66eb33.png">

It'd be nice for this package to upgrade its peer dependency to `prettier@2.x`. I tried to patch this via a [selective version resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/), but that didn't work.

**Comment by fvictorio** [comment]
Oh, that's bad :grimacing: I'll check if everything works fine with prettier v2 (it probably does) and fix this. Thanks Paul!

**Comment by PaulRBerg** [comment]
Thanks man!

**Comment by fvictorio** [comment]
Done, version `0.0.5` shouldn't show this warning. Let me know if it works for you.

**Comment by PaulRBerg** [comment]
Worked like a charm! Thanks.
