### ISSUE TITLE
Solhint not emitting errors

### ISSUE THREAD

**Issue by nventuro** [fvictorio/solhint-plugin-prettier#8]
Hello, thanks a lot for the work on this!

I'm finding that my prettier config causes it to alter the source code, and yet solhint emits no errors when the linter is run. I have the recommended config on my `.solhint.json` file:
```
{
  "extends": "solhint:recommended",
  "plugins": ["prettier"],
  "rules": {
    "prettier/prettier": "error",
    // other rules
  }
}
```

**Comment by fvictorio** [comment]
You mean there's a discrepancy between prettier and the plugin? Maybe it's not using the `.prettierrc` correctly, I'll take a look to see if I can reproduce it.

**Comment by fvictorio** [comment]
Hmm, it seems to be using the `.prettierrc` correctly, so I'll probably need some reproduction steps for this.

**Comment by nventuro** [comment]
The issue was I am running solhint without quotes around the glob, which led it to not parse all files, and is unrelated to the plugin. Thanks @fvictorio for helping me diagnose this!
